[pytest]
markers =
    topdown: Top-down integration tests (deselect with '-m "not topdown"')
    bottomup: Bottom-up integration tests (deselect with '-m "not bottomup"')
    sandwich: Sandwich integration tests (deselect with '-m "not sandwich"')
